excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://BibMartin.github.io
name: Bibmartin
description: Hosting ideas
author: Martin Journois
avatar: https://avatars1.githubusercontent.com/u/4586863?v=3&s=460
ga_domain: 
ga_tracking_id: 
